export const INVENTORY_PRODUCTS = [
  {
    id: '_1djojy2js',
    name: 'One Plus Earbuds',
    price: 2000,
    description:
      'This is One Plus product A product description is the marketing copy that explains what a product is and why its worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so theyre compelled to',
  },
  { id: '_wca1m3krd', name: 'Earphone', price: 1000, description: 'Sony The purpose of a product description is e purpose of a product description is to supply customers with important information about the features and benefits of the product so theyre compelled to Sony The features and benefits of the product so there compelled to' },
  { id: '_ahrb3n67z', name: 'Mouse', price: 200, description: 'Logitech product A product description is the marketing copy that explains what a product is and why its worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so theyre compelled to' },
  { id: '_exlomy3w3', name: 'Keyboard', price: 500, description: 'This product A product description is the marketing copy that explains what a product is and why its worth purchasing. The purpose of a product description is to supply customers with important information about the features and benefits of the product so theyre compelled to' },
  {
    id: '_q6n6w4sfb',
    name: 'Laptop',
    price: 900000,
    description: 'HP Dell Lenevo ',
  },
  { id: '_uu6dt6xrh', name: 'HDD', price: 2000, description: 'old drive' },
  {
    id: '_dx0r6jpxo',
    name: 'SSD',
    price: 5000,
    description: 'Speed performance',
  },
  {
    id: '_2a07n1ph1',
    name: 'product 1',
    description: 'product 1 description',
    price: 10,
  },
  {
    id: '_swdgfsdg',
    name: 'Product 2',
    description: 'Product 2 description',
    price: 34,
  },
  {
    id: '_sfddf234',
    name: 'mobile',
    description: 'mobile description',
    price: 50,
  },
  {
    id: '_e423js23',
    name: 'Product T',
    description: 'Product T description',
    price: 8,
  },
  {
    id: '_7e23js23',
    name: 'product Tablet',
    description: 'product Tablet description',
    price: 100,
  },
  {
    id: '_0e23js23',
    name: 'phone',
    description: 'phone description',
    price: 18,
  },
  {
    id: '_3nfag3kcq',
    name: 'Wireless charger',
    price: 4000,
    description: 'Galaxy note 1000',
  },
  {
    id: '_tmtinqdwj',
    name: 'logitech combo',
    price: 1000,
    description: 'key and mouse',
  },
  {
    id: '_gx39a6t2y',
    name: '1 plus',
    price: 1000,
    description: 'mobile brand',
  },
  {
    id: '_vjz5o95b4',
    name: 'Samrtwatch',
    price: 3000,
    description: 'Samsung smart watch description 1',
  },
  { id: '_bkgcw8anx', name: 'Notebook', price: 234546, description: 'dell' },
  {
    id: '_d94gjmir0',
    name: 'charger ',
    price: 3000,
    description: 'C Type 20V charger',
  },
  {
    id: '_t32ik4i9r',
    name: 'adpter',
    price: 2000,
    description: 'C Type adapter ',
  },
  {
    id: '_ks03r12q1',
    name: 'Motorola ',
    price: 200000,
    description: 'A AAAAA ',
  },
  {
    id: '_tfqzbtxl5',
    name: 'samsung',
    price: 120000,
    description: 'Samsung mobile description 1',
  },
  {
    id: '_2a07n1ph1',
    name: 'product 1',
    description: 'product 1 description',
    price: 10,
  },
  {
    id: '_swdgfsdg',
    name: 'Product 2',
    description: 'Product 2 description',
    price: 34,
  },
  {
    id: '_sfddf234',
    name: 'mobile',
    description: 'mobile description',
    price: 50,
  },
  {
    id: '_e423js23',
    name: 'Product T',
    description: 'Product T description',
    price: 8,
  },
  {
    id: '_7e23js23',
    name: 'product Tablet',
    description: 'product Tablet description',
    price: 100,
  },
  {
    id: '_0e23js23',
    name: 'phone',
    description: 'phone description',
    price: 18,
  },
  {
    id: '_2a07n1ph1He',
    name: 'product_ product 1',
    description: 'product 1 description',
    price: 10,
  },
  {
    id: '_swdgfsdgHe',
    name: 'product_ Product 2',
    description: 'Product 2 description',
    price: 34,
  },
  {
    id: '_sfddf234He',
    name: 'product_ mobile',
    description: 'mobile description',
    price: 50,
  },
  {
    id: '_e423js23He',
    name: 'product_ Product T',
    description: 'Product T description',
    price: 8,
  },
  {
    id: '_7e23js23He',
    name: 'product_ product Tablet',
    description: 'product Tablet description',
    price: 100,
  },
  {
    id: '_0e23js23He',
    name: 'product_ phone',
    description: 'phone description',
    price: 18,
  },
  {
    id: '_3nfag3kcqHe',
    name: 'product_ Wireless charger',
    price: 4000,
    description: 'Galaxy note 1000',
  },
  {
    id: '_tmtinqdwjHe',
    name: 'product_ logitech combo',
    price: 1000,
    description: 'key and mouse',
  },
  {
    id: '_gx39a6t2yHe',
    name: 'product_ 1 plus',
    price: 1000,
    description: 'mobile brand',
  },
  {
    id: '_vjz5o95b4He',
    name: 'product_ Samrtwatch',
    price: 3000,
    description: 'Samsung smart watch description 1',
  },
  {
    id: '_bkgcw8anxHe',
    name: 'product_ Notebook',
    price: 234546,
    description: 'dell',
  },
  {
    id: '_d94gjmir0He',
    name: 'product_ charger ',
    price: 3000,
    description: 'C Type 20V charger',
  },
  {
    id: '_t32ik4i9rHe',
    name: 'product_ adpter',
    price: 2000,
    description: 'C Type adapter ',
  },
  {
    id: '_1djojy2jsHe',
    name: 'product_ earbuds',
    price: 2000,
    description: 'Realme',
  },
  {
    id: '_wca1m3krdHe',
    name: 'product_ Earphone',
    price: 1000,
    description: 'Sony',
  },
  {
    id: '_ahrb3n67zHe',
    name: 'product_ Mouse',
    price: 200,
    description: 'Logitech',
  },
  {
    id: '_exlomy3w3He',
    name: 'product_ Keyboard',
    price: 500,
    description: 'HP',
  },
  {
    id: '_q6n6w4sfbHe',
    name: 'product_ Laptop',
    price: 900000,
    description: 'HP Dell Lenevo ',
  },
  {
    id: '_uu6dt6xrhHe',
    name: 'product_ HDD',
    price: 2000,
    description: 'old drive',
  },
  {
    id: '_dx0r6jpxoHe',
    name: 'product_ SSD',
    price: 5000,
    description: 'Speed performance',
  },
  {
    id: '_ks03r12q1He',
    name: 'product_ Motorola ',
    price: 200000,
    description: 'A AAAAA ',
  },
  {
    id: '_tfqzbtxl5He',
    name: 'product_ samsung',
    price: 120000,
    description: 'Samsung mobile description 1',
  },
  {
    id: '_2a07n1ph1He',
    name: 'product_ product 1',
    description: 'product 1 description',
    price: 10,
  },
  {
    id: '_swdgfsdgHe',
    name: 'product_ Product 2',
    description: 'Product 2 description',
    price: 34,
  },
  {
    id: '_sfddf234He',
    name: 'product_ mobile',
    description: 'mobile description',
    price: 50,
  },
  {
    id: '_e423js23He',
    name: 'product_ Product T',
    description: 'Product T description',
    price: 8,
  },
  {
    id: '_7e23js23He',
    name: 'product_ product Tablet',
    description: 'product Tablet description',
    price: 100,
  },
  {
    id: '_0e23js23He',
    name: 'product_ phone',
    description: 'phone description',
    price: 18,
  },
];
